name = "oid4vc-verifier-endpoint-hono"
compatibility_date = "2024-08-01"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "PRESENTATION_KV"
id = "cdf0c453ab064798957f56e006c78efc"

# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
